### ISSUE TITLE
Daily snapshots pull from server

### ISSUE THREAD

**Issue by Britcoin-Coder** [NebraLtd/snapshot-bumper#1]
Is it possible to host a daily snapshot of the blockchain and pull this directly from github on first boot? This may take a few minutes but it will making syncing for the end user ultra quick.

Perhaps need to have a pre installed snapshot anyway as a backup in case connection to github is not available.

This will alleviate the wen sync questions that are bound to come! 

bigdaveakers by the way - logged in with wrong account!

**Comment by ryanteck** [comment]
Resolved via discord.
